### PR TITLE
Win64 fixes to allow testing more than 4GB video memory

### PR DESCRIPTION
**Pull request by galkinvv**
-UL constants are 32 bit on win64, change to ULL
-change default vendor to NV64 + cuda8
-Advices about AMD env vars

### CODE REVIEW

**Comment by galkinvv** [comment]
Also I have prebuilt binaries for various 64-bit platfroms: https://github.com/galkinvv/memtestCL/tree/master/binaries

From my experience even the linux ones are quite portable.

I'd be happy to create a PR with them, however undestanding that PR with binaries nowdays looks "bad"... Should I create it?

**Comment by mirh** [comment]
Mhh no. You or @ihaque should put them in the release section.

**Comment by ihaque** [comment]
Thanks! This patch looks good to me; merging.

I appreciate the offer of binaries, but on principle I wouldn't feel comfortable putting my name to binaries generated outside my control. As the project is LGPL you are of course welcome to post binaries on your own and link back to the source here.

**Comment by galkinvv** [comment]
> but on principle I wouldn't feel comfortable putting my name to binaries generated outside my control. . As the project is LGPL you are of course welcome to post binaries on your own and link back to the source here.

I completely agree and understand. So, I've published my binaries under my name mentioning that the release is unofficial:
https://github.com/galkinvv/memtestCL/releases/tag/v2021.1.64bit-bins

**Pull request merged**
